# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 168421

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 6080:8080
